;;; pi-probe.el --- LLM-powered code understanding via LSP  -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; Author: <adithya>
;; Keywords: lsp, tools, convenience

;; This file is NOT part of GNU Emacs.

;;; Commentary:
;;
;; Integrates the pi-probe LSP server with Emacs via EGLOT.
;; The pi-probe server reads a pre-computed function-understanding.jsonl
;; file (generated by `bash analyze.sh') and serves rich LLM-generated
;; explanations via hover (Eldoc).
;;
;; Quick start:
;;   1. Ensure the JSONL exists:  cd ~/projects/pi-probe && bash analyze.sh
;;   2. Eval this file:           M-x load-file RET ~/.emacs.d/modules/pi-probe.el RET
;;   3. Open a source file        (e.g. *.ts, *.hs, *.md)
;;   4. M-x pi-probe-mode         -> activate pi-probe LSP
;;   5. Hover or C-h .            -> see LLM-generated explanation
;;   6. M-x pi-probe-mode         -> deactivate (restore normal LSP via M-x eglot)
;;
;;; Code:

(require 'eglot)
(require 'project)
(eval-when-compile (require 'cl-lib))

;; ── Customization ──────────────────────────────────────────────────

(defgroup pi-probe nil
  "LLM-powered code understanding via a lightweight LSP server."
  :group 'tools
  :prefix "pi-probe-")

(defcustom pi-probe-server-script nil
  "Absolute path to the pi-probe `lsp-server.mjs' script.
If nil, the module auto-detects it.
Set this to customize for a specific project."
  :type '(choice (const :tag "Auto-detect" nil)
                 (file :tag "Path to lsp-server.mjs"))
  :group 'pi-probe)

(defcustom pi-probe-understanding-file nil
  "Path to the `function-understanding.jsonl' file.
If nil, looks for it next to the server script, or uses the
UNDERSTANDING_FILE environment variable."
  :type '(choice (const :tag "Auto-detect" nil)
                 (file :tag "Path to function-understanding.jsonl"))
  :group 'pi-probe)

(defcustom pi-probe-auto-modes
  '(typescript-mode js-mode js-ts-mode haskell-mode markdown-mode gfm-mode
                    rust-mode python-mode go-mode c-mode c++-mode ruby-mode)
  "Major modes where pi-probe can be started."
  :type '(repeat symbol)
  :group 'pi-probe)

(defcustom pi-probe-show-why t
  "Whether to include design rationale (\"why\") in hover explanations.
When non-nil, symbols with a `why' field in the understanding JSONL
will display an additional \"WHY\" section explaining design decisions,
alternatives considered, and historical context."
  :type 'boolean
  :group 'pi-probe)

;; ── Internal state ─────────────────────────────────────────────────

(defvar pi-probe--original-server-programs nil
  "Saved `eglot-server-programs' before pi-probe modified it.")

;; ── Locate the server and JSONL ────────────────────────────────────

(defun pi-probe--find-script ()
  "Return the absolute path to lsp-server.mjs, or nil."
  (or pi-probe-server-script
      (locate-file "lsp-server.mjs" exec-path)
      (when-let* ((proj (project-current))
                  (root (project-root proj))
                  (script (expand-file-name "lsp-server.mjs" root)))
        (and (file-exists-p script) script))
      (let ((candidates (list (expand-file-name "~/projects/pi-probe/lsp-server.mjs")
                              (expand-file-name "~/src/pi-probe/lsp-server.mjs"))))
        (cl-find-if #'file-exists-p candidates))))

(defun pi-probe--find-jsonl ()
  "Return the absolute path to function-understanding.jsonl, or nil."
  (or pi-probe-understanding-file
      (getenv "UNDERSTANDING_FILE")
      (when-let* ((script (pi-probe--find-script))
                  (dir (file-name-directory script))
                  (jsonl (expand-file-name "function-understanding.jsonl" dir)))
        (and (file-exists-p jsonl) jsonl))
      (expand-file-name "function-understanding.jsonl"
                        (if-let* ((proj (project-current))
                                  (root (project-root proj)))
                            root
                          default-directory))))

(defun pi-probe--server-command ()
  "Return the command list (\"node\" \"/path/to/lsp-server.mjs\") or nil."
  (when-let ((script (pi-probe--find-script)))
    (list "node" script)))

(defun pi-probe--jsonl-exists-p ()
  "Return non-nil if the understanding JSONL file exists."
  (when-let ((jsonl (pi-probe--find-jsonl)))
    (file-exists-p jsonl)))

;; ── Start helper ───────────────────────────────────────────────────
;;
;; This EGLOT version has a new calling convention:
;;   (eglot MANAGED-MAJOR-MODES PROJECT CLASS CONTACT LANGUAGE-IDS)
;; where MANAGED-MAJOR-MODES is a list of major-mode symbols,
;; PROJECT is a project object, CLASS is eglot-lsp-server,
;; CONTACT is the server command list, and LANGUAGE-IDS is a list
;; of language-id strings.

(defun pi-probe--contact-eglot ()
  "Start the pi-probe LSP server via `eglot' with 5-arg calling convention.
Returns t if the server process was created, nil otherwise."
  (let* ((cmd (pi-probe--server-command))
         (jsonl (pi-probe--find-jsonl))
         (mode major-mode)
         (proj (project-current))
         (managed-modes (list mode)))
    (unless cmd
      (user-error "pi-probe: cannot locate lsp-server.mjs; customize `pi-probe-server-script'"))
    (unless (and jsonl (file-exists-p jsonl))
      (unless (yes-or-no-p
               (format "pi-probe: understanding file not found at %s.  Continue anyway? " jsonl))
        (user-error "Aborted")))
    (let* ((why-val (if pi-probe-show-why "true" "false"))
           (process-environment
            (cons (format "UNDERSTANDING_FILE=%s" (or jsonl ""))
                  (cons (format "PI_PROBE_SHOW_WHY=%s" why-val)
                        process-environment))))
      (eglot managed-modes proj eglot-lsp-server cmd
             (list (pi-probe--language-id mode)))
      t)))

(defun pi-probe--language-id (mode)
  "Return a language ID string for the given major-mode symbol."
  (let ((name (symbol-name mode)))
    (cond ((string-match-p "typescript\\|tsx\\|ts\\b" name) "typescript")
          ((string-match-p "javascript\\|jsx\\|js\\b" name) "javascript")
          ((string-match-p "haskell" name) "haskell")
          ((string-match-p "rust" name) "rust")
          ((string-match-p "markdown" name) "markdown")
          ((string-match-p "python" name) "python")
          ((string-match-p "go\\b" name) "go")
          ((string-match-p "\\`c-\\(?:c\\+\\+\\)?mode\\'" name) "c")
          ((string-match-p "\\`c\\+\\+" name) "cpp")
          ((string-match-p "ruby" name) "ruby")
          (t name))))

;; ── EGLOT registration ─────────────────────────────────────────────

;;;###autoload
(defun pi-probe-register ()
  "Register pi-probe in `eglot-server-programs'."
  (interactive)
  (let ((cmd (pi-probe--server-command)))
    (unless cmd
      (user-error "pi-probe: cannot locate lsp-server.mjs; customize `pi-probe-server-script'"))
    (setq pi-probe--original-server-programs (copy-tree eglot-server-programs))
    ;; Build mode spec: a list of mode symbols (with optional :language-id)
    ;; The new EGLOT supports lists of (MODE :language-id LANG) associations.
    (let* ((mode-spec
            (mapcar (lambda (m)
                      `(,m :language-id ,(pi-probe--language-id m)))
                    pi-probe-auto-modes)))
      (add-to-list 'eglot-server-programs `(,mode-spec . ,cmd)))
    (message "pi-probe: registered for %d modes" (length pi-probe-auto-modes))))

;;;###autoload
(defun pi-probe-unregister ()
  "Restore `eglot-server-programs' to its state before pi-probe registration."
  (interactive)
  (when pi-probe--original-server-programs
    (setq eglot-server-programs (copy-tree pi-probe--original-server-programs))
    (message "pi-probe: restored original eglot-server-programs"))
  (setq pi-probe--original-server-programs nil))

;; ── Start / Stop ───────────────────────────────────────────────────

;;;###autoload
(defun pi-probe-start ()
  "Start the pi-probe LSP server in the current buffer.
If another EGLOT server is active, it is replaced.
Sets UNDERSTANDING_FILE so the server loads the correct JSONL."
  (interactive)
  (when (eglot-managed-p)
    (eglot-shutdown (eglot--current-server-or-lose)))
  (pi-probe--contact-eglot)
  (message "pi-probe: LSP started in %s" (buffer-name)))

;;;###autoload
(defun pi-probe-stop ()
  "Stop the pi-probe LSP server in the current buffer."
  (interactive)
  (when (eglot-managed-p)
    (eglot-shutdown (eglot--current-server-or-lose))
    (message "pi-probe: stopped in %s" (buffer-name))))

;;;###autoload
(defun pi-probe-toggle ()
  "Toggle the pi-probe LSP server on/off in the current buffer."
  (interactive)
  (if (eglot-managed-p)
      (pi-probe-stop)
    (pi-probe-start)))

;;;###autoload
(defun pi-probe-restart ()
  "Restart the pi-probe LSP server (e.g. after re-running analyze.sh)."
  (interactive)
  (pi-probe-stop)
  (pi-probe-start))

;;;###autoload
(define-minor-mode pi-probe-why-mode
  "Toggle display of design rationale (\"why\") in pi-probe hover explanations.
When enabled (default), hovers show an additional \"WHY\" section with
design decisions, alternatives considered, and historical context.
When disabled, only the \"what\" (explanation) is shown.

The change takes effect the next time pi-probe is started or restarted."
  :lighter " π-why"
  :global nil
  :group 'pi-probe
  (setq-local pi-probe-show-why pi-probe-why-mode)
  (message "pi-probe-why-mode: %s — restart pi-probe for change to take effect"
           (if pi-probe-why-mode "ON (showing design rationale)" "OFF (explanation only)")))

;;;###autoload
(defun pi-probe-why-toggle ()
  "Toggle whether design rationale (\"why\") is shown in hover explanations.
Requires restart (M-x pi-probe-restart) to take effect."
  (interactive)
  (pi-probe-why-mode (if pi-probe-show-why -1 1)))

;; ── Minor Mode ─────────────────────────────────────────────────────

;;;###autoload
(define-minor-mode pi-probe-mode
  "Minor mode that connects the pi-probe LSP server in the current buffer.

When enabled, pi-probe provides rich LLM-generated hover explanations
via Eldoc.  Since EGLOT manages one server per buffer, this replaces
any existing EGLOT server.  Disable the mode and call `M-x eglot' to
restore your normal LSP."
  :lighter " π"
  :global nil
  :group 'pi-probe
  (cond (pi-probe-mode
         (pi-probe-start))
        ((eglot-managed-p)
         (pi-probe-stop))))

;;;###autoload
(defun pi-probe-ensure ()
  "Start pi-probe LSP if the current major mode matches `pi-probe-auto-modes'.
Intended for `find-file-hook' or project config."
  (interactive)
  (when (and (not (eglot-managed-p))
             (memq major-mode pi-probe-auto-modes)
             (pi-probe--find-script)
             (pi-probe--jsonl-exists-p))
    (pi-probe-start)))

;; ── Status and Diagnostics ─────────────────────────────────────────

;;;###autoload
(defun pi-probe-status ()
  "Display the current pi-probe connection status and file paths."
  (interactive)
  (message "%s pi-probe in «%s»\n  server: %s\n  jsonl:  %s"
           (if (eglot-managed-p) "✅" "⊘")
           (buffer-name)
           (or (pi-probe--find-script) "(not found)")
           (or (pi-probe--find-jsonl) "(not found)")))

;;;###autoload
(defun pi-probe-list-symbols ()
  "List all symbols indexed by pi-probe in a dedicated buffer."
  (interactive)
  (let ((jsonl (pi-probe--find-jsonl)))
    (unless (and jsonl (file-exists-p jsonl))
      (user-error "pi-probe: understanding file not found at %s" jsonl))
    (with-temp-buffer
      (insert-file-contents jsonl)
      (let ((names ()))
        (goto-char (point-min))
        (while (re-search-forward (rx "\"name\":\"" (group (+? (not "\""))) "\"") nil t)
          (push (match-string-no-properties 1) names))
        (unless names
          (user-error "pi-probe: no symbols found in %s" jsonl))
        (setq names (seq-uniq names #'string=))
        (pop-to-buffer (get-buffer-create "*pi-probe symbols*"))
        (let ((inhibit-read-only t))
          (erase-buffer)
          (dolist (n (sort names #'string-lessp))
            (insert n "\n"))
          (goto-char (point-min)))
        (special-mode)
        (setq-local revert-buffer-function
                    (lambda (&rest _) (pi-probe-list-symbols)))
        (message "pi-probe: %d unique symbols indexed" (length names))))))

;; ── Project integration ────────────────────────────────────────────

;;;###autoload
(defun pi-probe-project-has-jsonl-p ()
  "Return non-nil if the current project has a pi-probe understanding file."
  (when-let ((jsonl (pi-probe--find-jsonl)))
    (file-exists-p jsonl)))

;;;###autoload
(defun pi-probe-dir-locals-adjust ()
  "Write a `.dir-locals.el' that enables pi-probe in the current project."
  (interactive)
  (when-let* ((proj (project-current))
              (root (project-root proj))
              (script (pi-probe--find-script))
              (jsonl (pi-probe--find-jsonl)))
    (let ((dir-locals-file (expand-file-name ".dir-locals.el" root))
          (content
           (prin1-to-string
            `((nil . ((pi-probe-server-script . ,script)
                      (pi-probe-understanding-file . ,jsonl)
                      (eval . (pi-probe-mode 1))))))))
      (with-temp-file dir-locals-file
        (insert ";;; Directory Local Variables -*- lexical-binding: t -*-\n")
        (insert ";; For more information: (info \"(emacs) Directory Variables\")\n\n")
        (insert content "\n"))
      (message "pi-probe: wrote %s" dir-locals-file))))

;; ── Self-test ──────────────────────────────────────────────────────

;;;###autoload
(defun pi-probe-self-test ()
  "Run a quick smoke test of the pi-probe integration.
Checks paths, starts the server, and reports status."
  (interactive)
  (let ((script (pi-probe--find-script))
        (jsonl (pi-probe--find-jsonl)))
    (message "═ pi-probe self-test ═══════════════════════════════")
    (message "  server script:  %s" (or script "✗ NOT FOUND"))
    (message "  understanding:  %s" (if (and jsonl (file-exists-p jsonl))
                                        (format "%s (%d bytes)"
                                                jsonl
                                                (file-attribute-size (file-attributes jsonl)))
                                      "✗ NOT FOUND"))
    (message "  major mode:     %s" major-mode)
    (message "  eglot-managed-p: %s" (eglot-managed-p))
    (when (and script jsonl (file-exists-p jsonl))
      (condition-case err
          (progn
            (pi-probe-start)
            ;; In interactive Emacs, eglot-managed-p will be t after the
            ;; LSP handshake completes.  In batch mode we at least verify
            ;; the process was spawned.
            (let ((server-procs
                   (cl-remove-if-not
                    (lambda (p) (string-match-p "pi-probe\\|EGLOT" (process-name p)))
                    (process-list))))
              (if server-procs
                  (message "  ✅ LSP server process running: %s"
                           (mapconcat #'process-name server-procs ", "))
                (message "  ⚠️  No server process found (may be delayed in batch mode)")))
            (message "  ✅ pi-probe self-test passed"))
        (error
         (message "  ❌ Test failed: %s" (error-message-string err)))))
    (message "═══════════════════════════════════════════════════")))

;; ── Autoload registration ─────────────────────────────────────────

(pi-probe-register)

(provide 'pi-probe)
;;; pi-probe.el ends here
